### ISSUE TITLE
为什么要弄个空类指定lib名呢？

### ISSUE THREAD

**Issue by xxw8393** [qibin0506/Module2Module#1]
在RouterManager里将所有的类自动生成一个HashMap来查找不是更方便？

**Comment by qibin0506** [comment]
原因是这样的： 在多个模块中都会自动生成一个路由表， 如果不做区分， 那么这些路由表的类名都是相同的， 当用主模块compile进所有子模块的的时候就会造成类名冲突，解决这个问题的方式就是每个module自动生成的路由表类名不同，解决方法就是建立一个空类（或者不建立也可以，选择该模块中任意一个类也可以）通过注解的方式指定一个类名，这样每个子module的路由表就是不会冲突了。具体可查看源码：[RouterProcessor](https://github.com/qibin0506/Module2Module/blob/master/Module2Module/routerhelper/src/main/java/org/loader/router/helper/RouterProcessor.java)
