### ISSUE TITLE
App模块Application中，路由pattern写入有误

### ISSUE THREAD

**Issue by puhaojie** [qibin0506/Module2Module#2]
例子setupRouter函数中如下

    private void setupRouter() {
        RouterHelper.install();
//        Router.router(ActivityRule.ACTIVITY_SCHEME + "shop.main", ShopActivity.class);
//        Router.router(ActivityRule.ACTIVITY_SCHEME + "bbs.main", BBSActivity.class);
    }

改为手动注册时候，从shop模块跳转不到bbs模块，查明原因后发现ShopActivity跳转逻辑如下
if (Router.resolveRouter(ActivityRule.ACTIVITY_SCHEME + "org.loader.bbslib.BBSActivity")) {
                    Intent it = org.loader.router.Router.invoke(ShopActivity.this, ActivityRule.ACTIVITY_SCHEME + "org.loader.bbslib.BBSActivity");
                    startActivity(it);
   }
注册的key和查找的key存在不一致的情况
我将注册改成：
Router.router(ActivityRule.ACTIVITY_SCHEME + "org.loader.bbslib.BBSActivity", BBSActivity.class);
就可以了

**Comment by qibin0506** [comment]
已修改
